# Generated by Django 5.1.3 on 2024-12-12 13:18

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryimage',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Menu categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_data',
            field=models.JSONField(default=dict, help_text='Complete menu structure including categories and items'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='myapp.menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='business_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_type', models.CharField(choices=[('menu', 'Menu Image'), ('general', 'General Image')], default='general', max_length=10)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='images',
            field=models.ManyToManyField(blank=True, to='myapp.menuimage'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='TemporaryImage',
        ),
    ]
