# Generated by Django 5.1.3 on 2024-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_temporaryimage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='options',
            field=models.JSONField(blank=True, help_text='JSON field to store optional extras or variations', null=True),
        ),
    ]
