# Generated by Django 5.1.3 on 2024-12-13 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menuitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='myapp.menu'),
        ),
    ]
