# Generated by Django 5.1.3 on 2024-12-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_active_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
