# Generated by Django 5.1.3 on 2024-12-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_menucategory_deletable'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
