# Generated by Django 5.1.3 on 2024-12-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_menuimage_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='images',
            field=models.ManyToManyField(blank=True, to='myapp.menuimage'),
        ),
    ]
