# Generated by Django 5.1.3 on 2024-12-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_menucategory_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='myapp.menu')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
