# Generated by Django 5.1.3 on 2024-12-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_menuscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_month_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='processings_this_month',
            field=models.IntegerField(default=0, help_text='Number of processings this month'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_processings',
            field=models.IntegerField(default=0, help_text='Total number of menu processings'),
        ),
    ]
