# Generated by Django 5.1.3 on 2024-12-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_template_publishedmenu_templateanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('css_content', models.TextField()),
                ('js_content', models.TextField(blank=True)),
                ('config', models.JSONField()),
            ],
        ),
    ]
