# Generated by Django 5.1.3 on 2024-12-17 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_menutemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutemplate',
            name='config',
        ),
        migrations.AddField(
            model_name='menutemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menutemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menutemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menutemplate',
            name='css_content',
            field=models.TextField(help_text='CSS for styling the menu'),
        ),
        migrations.AlterField(
            model_name='menutemplate',
            name='html_content',
            field=models.TextField(help_text='HTML template content'),
        ),
        migrations.AlterField(
            model_name='menutemplate',
            name='js_content',
            field=models.TextField(blank=True, help_text='Optional JavaScript', null=True),
        ),
        migrations.AlterField(
            model_name='menutemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
