# Generated by Django 5.1.3 on 2024-12-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_menutemplate_config_menutemplate_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedmenu',
            name='subdomain',
        ),
        migrations.AddField(
            model_name='publishedmenu',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
