# Generated by Django 5.1.3 on 2024-12-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_publishedmenu_subdomain_publishedmenu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
