# Generated by Django 5.1.3 on 2024-12-26 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_menuimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
