# Generated by Django 5.1.3 on 2024-12-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_menuimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='css_template',
            field=models.TextField(blank=True, help_text='Base CSS styles', null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='html_template',
            field=models.TextField(blank=True, help_text='Base HTML template', null=True),
        ),
    ]
